-- Identity Shield — quarterly auto-generated threat-landscape reports.
--
-- The meta-analyst's quarterly output. One row per (period_start,
-- period_end) pair. Generated by the threatLandscapeAnalyst worker
-- (I-P6) once per calendar quarter; surfaced to admin via
-- /v1/admin/intel/briefings/latest.
--
-- BRIEFING CONTENT (body_markdown):
-- A narrative report covering:
--   - underground migration patterns: "this quarter the carding
--     scene migrated from @oldhandle to @newhandle"
--   - top 5 emerging channels by yield
--   - top 5 declining channels (recommended for status=dormant)
--   - geographic distribution shift (US dominance → US+UK+AU pivot)
--   - new scam-type emergence (e.g., AI-voice-cloning scripts
--     appearing in dox-for-hire channels)
--   - active_threats production rate per source-kind
--
-- METRICS_JSONB:
-- Structured companion to the narrative. Drives any charts in the
-- admin UI and lets a future operator compare quarters
-- programmatically. Conventional shape:
--   {
--     "channels_added": <int>,
--     "channels_removed": <int>,
--     "channels_dormant_flagged": <int>,
--     "active_threats_produced": <int>,
--     "top_capability_tags": [{"tag": "carding", "count": N}, ...],
--     "geo_distribution": {"US": N, "UK": N, ...},
--     "candidate_queue_throughput": {"discovered": N, "approved": N,
--       "rejected": N, "pending_at_end": N}
--   }
-- JSONB shape is intentionally not constrained — the meta-analyst
-- evolves it over time.
--
-- THE PITCH-DECK SLIDE LIVES HERE:
-- "We don't hire ex-FBI analysts. We hire the LLM that does the job
-- better — and we ship it to a hundred thousand phones." The
-- existence of this table is what makes that line true. Constella /
-- Flashpoint deliver this as a PDF report from their analyst team.
-- AegisDial delivers it as a markdown row, auto-generated, refreshed
-- quarterly, available via admin API.
--
-- PRIVACY POSTURE:
-- Aggregate-only. No user PII. No specific artifact values (the
-- briefing references channel handles and capability tags but not
-- the per-message active_threats rows). Safe to export.
--
-- RETENTION: indefinite. Historical briefings are valuable for the
-- fundraise story ("here's our threat-intel posture across 8 quarters
-- — note the consistent improvement") and for operator pattern-
-- spotting across years.
--
-- Idempotent + additive.

CREATE TABLE IF NOT EXISTS threat_landscape_briefings (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Inclusive start of the quarter (e.g., 2026-01-01 for Q1 2026).
  period_start              DATE NOT NULL,
  -- Inclusive end of the quarter (e.g., 2026-03-31 for Q1 2026).
  period_end                DATE NOT NULL,
  -- Wall-clock when the worker generated this row. May be days after
  -- period_end (the worker runs on the first Monday of the new
  -- quarter to allow for late-arriving data classification).
  generated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- The narrative report. Rendered in the admin UI as markdown.
  -- Multi-page; not size-capped at the schema layer.
  body_markdown             TEXT NOT NULL,
  -- Structured metrics companion. Conventional shape in header.
  metrics_jsonb             JSONB NOT NULL,
  -- One briefing per quarter. Re-runs (operator-forced regeneration)
  -- UPDATE via ON CONFLICT (period_start, period_end).
  UNIQUE (period_start, period_end)
);

COMMENT ON TABLE threat_landscape_briefings IS
  'Identity Shield — quarterly auto-generated threat-landscape narratives + structured metrics. Generated by the threatLandscapeAnalyst worker; surfaced via /v1/admin/intel/briefings/latest. The "we replaced an ex-FBI analyst team with an LLM and shipped it to a hundred thousand phones" pitch-deck claim is operationalized by the existence of this table.';

COMMENT ON COLUMN threat_landscape_briefings.body_markdown IS
  'Narrative report covering underground migration patterns, top emerging/declining channels, geographic distribution shifts, new scam-type emergence, and active_threats production rates. Rendered as markdown in the admin UI; suitable for direct export to fundraise materials.';

COMMENT ON COLUMN threat_landscape_briefings.metrics_jsonb IS
  'Structured companion to body_markdown. Conventional keys: channels_added/removed/dormant_flagged, active_threats_produced, top_capability_tags, geo_distribution, candidate_queue_throughput. Shape evolves with the meta-analyst (no schema constraint).';
