import type { FastifyInstance, FastifyRequest } from 'fastify';
import { requireBearer } from '../lib/auth.js';
import { query, withTx } from '../lib/db.js';
import { emitMetric } from '../lib/observability.js';
import { withAdminAudit } from './adminAudit.js';

// Identity Shield — I-P7 — operator dashboard + intel-source health
// + AI-meta-analyst candidate-review surface.
//
// Mirrors the convention from Email Shield P23 (adminEmailShield.ts)
// and Recovery Shield R-P6 (adminRecoveryShield.ts):
//   - Auth: `requireBearer` shared-secret gate (same surface every
//     other admin route uses)
//   - Audit + 500 sanitization: `withAdminAudit` wraps every handler
//     so a thrown pg error can't leak SQL fragments through the bearer
//     surface and every successful read emits the structured audit log
//     + access metric
//   - Read-only by default; mutations only on candidate approve/reject
//   - Time-bounded SQL: every aggregate query is scoped by a literal
//     INTERVAL clause — no "all rows ever" scans
//   - No per-user PII: aggregate counts only. `threat_value` (a
//     phone/email/wallet that a known scammer uses) is operator-
//     sensitive but acceptable in admin contexts — it's surfaced from
//     /active-threats-distribution ONLY when the caller explicitly
//     passes ?include_values=true, default OFF. Briefing body_markdown
//     IS returned verbatim because it's auto-generated by the LLM
//     meta-analyst from aggregate stats (no per-user PII enters the
//     prompt; see threatLandscapeAnalyst.ts). The I-P8 adversarial
//     review will verify a digit-redaction pass on the LLM output as
//     defense-in-depth — flagged in route comments below for that
//     phase.
//
// ADMIN-ACTOR TRACKING DEVIATION (documented for the future
// admin-user model):
// The bearer secret authenticates the operator but isn't tied to a
// user_id. `threat_intel_candidates.decided_by` is therefore stored
// as NULL on approve/reject in v1 — there is no admin-user table to
// reference. The act-of-decision is still logged via withAdminAudit
// (correlation_id + operator header), which is the forensic trail
// the bearer surface relies on across every other /v1/admin/* route.
// I-P8 + the future admin-user model will retrofit decided_by once
// per-operator identity exists. See RECOVERY_AND_IDENTITY_SHIELDS.md
// §12 ("AI-as-analyst") for the strategic context: "Jesiah-as-
// strategic-approver" is the editorial half of the wedge, not a
// per-user-account half.

// Panels (read-only):
//   1. GET  /v1/admin/identity-shield/summary
//   2. GET  /v1/admin/identity-shield/breaches-timeline
//   3. GET  /v1/admin/identity-shield/active-threats-distribution
//   4. GET  /v1/admin/identity-shield/intel-source-health
//
// Candidate-queue (mixed read + mutate):
//   5. GET  /v1/admin/intel/candidates
//   6. POST /v1/admin/intel/candidates/:id/approve
//   7. POST /v1/admin/intel/candidates/:id/reject
//
// Briefings (read-only):
//   8. GET  /v1/admin/intel/briefings/latest
//   9. GET  /v1/admin/intel/briefings
//  10. GET  /v1/admin/intel/briefings/:id

// -----------------------------------------------------------------
// Response shape types
// -----------------------------------------------------------------

interface SummaryResponse {
  monitors_active_total: number;
  monitors_by_kind: Record<
    'email' | 'phone_e164' | 'ssn_last4_hash' | 'dob_hash' | 'name_address_hash',
    number
  >;
  findings_7d_by_severity: Record<'informational' | 'caution' | 'critical', number>;
  findings_30d_by_severity: Record<'informational' | 'caution' | 'critical', number>;
  active_threats_by_severity: Record<
    'informational' | 'caution' | 'warning' | 'confirmed_scammer',
    number
  >;
  intel_ingest_health: {
    last_hibp_sync_at: string | null;
    last_enzoic_sync_at: string | null;
    last_telegram_poll_at: string | null;
    last_darknet_crawl_at: string | null;
  };
}

interface TimelineDay {
  date: string;
  findings_count: number;
  by_severity: { informational: number; caution: number; critical: number };
}

interface ActiveThreatsDistributionRow {
  severity: string;
  provenance_prefix: string;
  count: number;
  threat_values?: string[];
}

interface IntelSourceHealthRow {
  id: string;
  source_kind: 'telegram' | 'darknet_market';
  source_handle: string;
  display_name: string;
  status: string;
  last_message_observed_at: string | null;
  classified_message_count_7d: number;
  active_threats_produced_7d: number;
}

interface CandidateRow {
  id: string;
  source_kind: 'telegram' | 'darknet_market';
  source_handle: string;
  discovered_at: string;
  rationale: unknown;
  candidate_score: number;
  decision: string | null;
  decided_at: string | null;
}

interface BriefingSummaryRow {
  id: string;
  period_start: string;
  period_end: string;
  generated_at: string;
}

interface BriefingFullRow extends BriefingSummaryRow {
  body_markdown: string;
  metrics_jsonb: unknown;
}

// -----------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------

/** Parse Date | string into ISO. Returns null when input is null/undefined. */
function isoOrNull(v: Date | string | null | undefined): string | null {
  if (v === null || v === undefined) return null;
  const d = v instanceof Date ? v : new Date(v);
  return Number.isNaN(d.getTime()) ? null : d.toISOString();
}

/**
 * Pull the source-tag prefix off a free-form provenance string.
 * `telegram_channel:abc123:msg456` → `telegram_channel`. Mirrors the
 * convention codified in migration 071's header. Unknown shapes fall
 * back to 'unknown' rather than leaking the raw provenance into the
 * distribution rollup.
 */
function provenancePrefix(p: string): string {
  const colon = p.indexOf(':');
  if (colon === -1) return 'unknown';
  const prefix = p.slice(0, colon);
  // Whitelist — only these prefixes are valid distribution buckets.
  // Anything else (a malformed provenance from a future migration)
  // is bucketed as 'unknown' so the dashboard never invents a label.
  const KNOWN = new Set([
    'aegisdial_recovery',
    'telegram_channel',
    'darknet_market',
    'enzoic_breach',
    'hibp',
  ]);
  return KNOWN.has(prefix) ? prefix : 'unknown';
}

/** UUID v4 / v8 shape — same loose regex Live Shield v4 routes use. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function isUuid(s: string): boolean {
  return UUID_RE.test(s);
}

/**
 * I-M4 (adversarial defense-in-depth): redact digit-runs and
 * email-shaped patterns out of LLM-generated briefing markdown
 * before it lands in the operator response.
 *
 * The upstream prompt (threatLandscapeAnalyst.ts BRIEFING_SYSTEM_PROMPT)
 * already sanitizes inputs — no per-user PII is supposed to reach the
 * model. But the LLM is non-deterministic: it could hallucinate a
 * digit-run that PATTERN-matches a phone number or SSN, even when
 * the input had none. This route is the last line before that
 * surfaces to an admin browser, so we scrub here too.
 *
 * Rules:
 *   - Runs of 4+ digits → "[REDACTED]" (catches phone/SSN/CC patterns
 *     without false-positiving on short pwn-count counters like
 *     "12 channels" or "1 briefing").
 *   - Email-shaped tokens → "[REDACTED-EMAIL]" (the local-part +
 *     "@" + domain pattern, generic enough to catch hallucinated
 *     usernames).
 *
 * Returns the redacted body along with a count of how many
 * replacements ran — the route can surface this so an operator
 * notices a sudden spike (which would indicate either a prompt
 * regression or a real PII leak in the upstream pipeline).
 */
export function redactBriefingBody(body: string): { redacted: string; redactions: number } {
  let redactions = 0;
  // Email first — otherwise the digit-run pass would scrub the
  // numeric tail of an email-shaped local part before the email
  // regex could fire on the whole token.
  let redacted = body.replace(/\b[\w._%+-]+@[\w.-]+\.[A-Za-z]{2,}\b/g, () => {
    redactions++;
    return '[REDACTED-EMAIL]';
  });
  redacted = redacted.replace(/\b\d{4,}\b/g, () => {
    redactions++;
    return '[REDACTED]';
  });
  return { redacted, redactions };
}

/**
 * Parse `?limit=N` from a Fastify request, clamped to [1, max].
 * Returns the default when the param is missing or malformed.
 */
function parseLimit(req: FastifyRequest, def: number, max: number): number {
  const q = req.query as Record<string, string | undefined> | undefined;
  const raw = q?.['limit'];
  if (!raw) return def;
  const n = parseInt(raw, 10);
  if (!Number.isFinite(n) || n <= 0) return def;
  return Math.min(n, max);
}

// -----------------------------------------------------------------
export async function adminIdentityShieldRoutes(app: FastifyInstance): Promise<void> {
  // ===============================================================
  // 1. GET /v1/admin/identity-shield/summary
  // ===============================================================
  // Top-level operator counters across the Identity Shield surface:
  // how many monitors are live, how many findings have surfaced over
  // 7d and 30d (split by severity), what active_threats look like
  // right now, and what each ingest source's last-known-good
  // timestamp is.
  //
  // Every sub-query is time-bounded (last 30d) and groups on indexed
  // columns. The intel_ingest_health block reads MAX() timestamps
  // from the metric_counters table for the cross-source heartbeat —
  // each ingest worker emits its own progress metric, and the admin
  // surfaces the most recent bucket per source.
  app.get(
    '/v1/admin/identity-shield/summary',
    { preHandler: requireBearer },
    withAdminAudit('identity-shield-summary', async (_req, reply) => {
      void emitMetric('identity_shield.admin_view_summary', {});

      // (a) Active monitors total + per-kind breakdown.
      const monitorsRes = await query<{ monitor_kind: string; count: string }>(
        `SELECT monitor_kind, COUNT(*)::TEXT AS count
           FROM identity_monitors
          WHERE active
          GROUP BY monitor_kind`,
      );
      const monitors_by_kind: SummaryResponse['monitors_by_kind'] = {
        email: 0,
        phone_e164: 0,
        ssn_last4_hash: 0,
        dob_hash: 0,
        name_address_hash: 0,
      };
      let monitors_active_total = 0;
      for (const r of monitorsRes.rows) {
        const n = parseInt(r.count, 10) || 0;
        if (r.monitor_kind in monitors_by_kind) {
          monitors_by_kind[r.monitor_kind as keyof typeof monitors_by_kind] = n;
        }
        monitors_active_total += n;
      }

      // (b) Findings 7d + 30d by severity (single query, two FILTERs
      // per severity bucket).
      const findingsRes = await query<{
        severity: 'informational' | 'caution' | 'critical';
        count_7d: string;
        count_30d: string;
      }>(
        `SELECT severity,
                COUNT(*) FILTER (WHERE surfaced_at >= NOW() - INTERVAL '7 days')::TEXT  AS count_7d,
                COUNT(*) FILTER (WHERE surfaced_at >= NOW() - INTERVAL '30 days')::TEXT AS count_30d
           FROM identity_breach_findings
          WHERE surfaced_at >= NOW() - INTERVAL '30 days'
          GROUP BY severity`,
      );
      const findings_7d_by_severity: SummaryResponse['findings_7d_by_severity'] = {
        informational: 0,
        caution: 0,
        critical: 0,
      };
      const findings_30d_by_severity: SummaryResponse['findings_30d_by_severity'] = {
        informational: 0,
        caution: 0,
        critical: 0,
      };
      for (const r of findingsRes.rows) {
        if (r.severity in findings_7d_by_severity) {
          findings_7d_by_severity[r.severity] = parseInt(r.count_7d, 10) || 0;
          findings_30d_by_severity[r.severity] = parseInt(r.count_30d, 10) || 0;
        }
      }

      // (c) Active threats — current snapshot (NOT 30d-bounded; this
      // is the live working set the scorers query). Excludes expired.
      const threatsRes = await query<{ severity: string; count: string }>(
        `SELECT severity, COUNT(*)::TEXT AS count
           FROM active_threats
          WHERE (expires_at IS NULL OR expires_at > NOW())
          GROUP BY severity`,
      );
      const active_threats_by_severity: SummaryResponse['active_threats_by_severity'] = {
        informational: 0,
        caution: 0,
        warning: 0,
        confirmed_scammer: 0,
      };
      for (const r of threatsRes.rows) {
        if (r.severity in active_threats_by_severity) {
          active_threats_by_severity[
            r.severity as keyof typeof active_threats_by_severity
          ] = parseInt(r.count, 10) || 0;
        }
      }

      // (d) Intel-source heartbeat. Each ingest worker emits its
      // progress metric on every successful pass; we report the most
      // recent bucket per worker. metric_counters is keyed by
      // (name, tags, bucket). Window is 30 days — anything older
      // than that is treated as "no recent sync."
      //
      // Metric name conventions (verified against ingest workers):
      //   identity_shield.hibp_sync           (HIBP delta worker)
      //   identity_shield.enzoic_sync         (Enzoic batch worker)
      //   identity_shield.telegram_poll       (Telegram listener)
      //   identity_shield.darknet_crawl       (Tor crawler)
      const heartbeatRes = await query<{ name: string; latest: Date | null }>(
        `SELECT name, MAX(bucket) AS latest
           FROM metric_counters
          WHERE name IN (
                  'identity_shield.hibp_sync',
                  'identity_shield.enzoic_sync',
                  'identity_shield.telegram_poll',
                  'identity_shield.darknet_crawl'
                )
            AND bucket >= NOW() - INTERVAL '30 days'
          GROUP BY name`,
      );
      const heartbeat: Record<string, string | null> = {
        'identity_shield.hibp_sync': null,
        'identity_shield.enzoic_sync': null,
        'identity_shield.telegram_poll': null,
        'identity_shield.darknet_crawl': null,
      };
      for (const r of heartbeatRes.rows) {
        heartbeat[r.name] = isoOrNull(r.latest);
      }

      const body: SummaryResponse = {
        monitors_active_total,
        monitors_by_kind,
        findings_7d_by_severity,
        findings_30d_by_severity,
        active_threats_by_severity,
        intel_ingest_health: {
          last_hibp_sync_at: heartbeat['identity_shield.hibp_sync'] ?? null,
          last_enzoic_sync_at: heartbeat['identity_shield.enzoic_sync'] ?? null,
          last_telegram_poll_at: heartbeat['identity_shield.telegram_poll'] ?? null,
          last_darknet_crawl_at: heartbeat['identity_shield.darknet_crawl'] ?? null,
        },
      };
      return reply.send(body);
    }),
  );

  // ===============================================================
  // 2. GET /v1/admin/identity-shield/breaches-timeline
  // ===============================================================
  // Per-day buckets, last 30 days, UTC: identity_breach_findings
  // counts, with per-severity sub-counts. Drives the operator's
  // "are we surfacing breaches consistently or is the ingest
  // worker stalled?" view.
  app.get(
    '/v1/admin/identity-shield/breaches-timeline',
    { preHandler: requireBearer },
    withAdminAudit('identity-shield-breaches-timeline', async (_req, reply) => {
      void emitMetric('identity_shield.admin_view_breaches_timeline', {});

      const res = await query<{
        bucket: Date;
        total: string;
        informational: string;
        caution: string;
        critical: string;
      }>(
        `SELECT
           date_trunc('day', surfaced_at AT TIME ZONE 'UTC') AS bucket,
           COUNT(*)::TEXT                                              AS total,
           COUNT(*) FILTER (WHERE severity = 'informational')::TEXT    AS informational,
           COUNT(*) FILTER (WHERE severity = 'caution')::TEXT          AS caution,
           COUNT(*) FILTER (WHERE severity = 'critical')::TEXT         AS critical
         FROM identity_breach_findings
         WHERE surfaced_at >= NOW() - INTERVAL '30 days'
         GROUP BY bucket
         ORDER BY bucket ASC
         LIMIT 30`,
      );
      const days: TimelineDay[] = res.rows.map((r) => {
        const d = r.bucket instanceof Date ? r.bucket : new Date(r.bucket);
        return {
          date: d.toISOString().slice(0, 10),
          findings_count: parseInt(r.total, 10) || 0,
          by_severity: {
            informational: parseInt(r.informational, 10) || 0,
            caution: parseInt(r.caution, 10) || 0,
            critical: parseInt(r.critical, 10) || 0,
          },
        };
      });
      return reply.send({ days, window_days: 30, tz: 'UTC' });
    }),
  );

  // ===============================================================
  // 3. GET /v1/admin/identity-shield/active-threats-distribution
  // ===============================================================
  // Two cross-tabulations on the live (non-expired) active_threats
  // working set: by severity, by provenance source-prefix. Default
  // response is aggregate-counts-only.
  //
  // PII GUARD: `threat_value` columns (the phone/email/wallet) are
  // operator-sensitive. They're surfaced ONLY when the caller passes
  // `?include_values=true` — an explicit opt-in that the audit log
  // captures via the query-string sub-tag below. Default OFF means a
  // simple curl of this route can't accidentally exfiltrate the
  // working set of scam phone numbers. Even with include_values=true,
  // we cap at 5 sample values per bucket to bound response size.
  app.get(
    '/v1/admin/identity-shield/active-threats-distribution',
    { preHandler: requireBearer },
    withAdminAudit('identity-shield-active-threats-distribution', async (req, reply) => {
      const q = (req.query as Record<string, string | undefined> | undefined) ?? {};
      const includeValues = q['include_values'] === 'true';
      void emitMetric('identity_shield.admin_view_active_threats_distribution', {
        include_values: includeValues ? 'true' : 'false',
      });

      // (a) By severity.
      const sevRes = await query<{ severity: string; count: string }>(
        `SELECT severity, COUNT(*)::TEXT AS count
           FROM active_threats
          WHERE (expires_at IS NULL OR expires_at > NOW())
          GROUP BY severity`,
      );
      const by_severity: Record<string, number> = {
        informational: 0,
        caution: 0,
        warning: 0,
        confirmed_scammer: 0,
      };
      for (const r of sevRes.rows) {
        if (r.severity in by_severity) {
          by_severity[r.severity] = parseInt(r.count, 10) || 0;
        }
      }

      // (b) By provenance prefix. We pull (provenance, count) and
      // bucket in JS using provenancePrefix() so a future provenance
      // shape (e.g. 'new_source:...') doesn't break the rollup.
      const provRes = await query<{ provenance: string; count: string }>(
        `SELECT provenance, COUNT(*)::TEXT AS count
           FROM active_threats
          WHERE (expires_at IS NULL OR expires_at > NOW())
          GROUP BY provenance`,
      );
      const provBuckets = new Map<string, number>();
      for (const r of provRes.rows) {
        const prefix = provenancePrefix(r.provenance);
        provBuckets.set(prefix, (provBuckets.get(prefix) ?? 0) + (parseInt(r.count, 10) || 0));
      }

      const provenanceRows: ActiveThreatsDistributionRow[] = [];
      for (const [prefix, count] of provBuckets) {
        provenanceRows.push({
          severity: 'all',
          provenance_prefix: prefix,
          count,
        });
      }
      provenanceRows.sort((a, b) => b.count - a.count);

      // (c) Sample values — only when explicitly requested. Cap at 5
      // per (severity, prefix) bucket to bound size + audit cost.
      let by_severity_samples: Record<string, string[]> | undefined;
      let by_provenance_samples: Record<string, string[]> | undefined;
      if (includeValues) {
        const sampleRes = await query<{
          severity: string;
          provenance: string;
          threat_value: string;
        }>(
          `SELECT severity, provenance, threat_value
             FROM active_threats
            WHERE (expires_at IS NULL OR expires_at > NOW())
            ORDER BY last_seen_at DESC
            LIMIT 500`,
        );
        by_severity_samples = {};
        by_provenance_samples = {};
        for (const r of sampleRes.rows) {
          const sev = r.severity;
          const prov = provenancePrefix(r.provenance);
          if (!by_severity_samples[sev]) by_severity_samples[sev] = [];
          if (!by_provenance_samples[prov]) by_provenance_samples[prov] = [];
          if (by_severity_samples[sev].length < 5) by_severity_samples[sev].push(r.threat_value);
          if (by_provenance_samples[prov].length < 5) by_provenance_samples[prov].push(r.threat_value);
        }
      }

      return reply.send({
        by_severity,
        by_provenance: provenanceRows.map((r) => ({
          provenance_prefix: r.provenance_prefix,
          count: r.count,
        })),
        include_values: includeValues,
        by_severity_samples,
        by_provenance_samples,
      });
    }),
  );

  // ===============================================================
  // 4. GET /v1/admin/identity-shield/intel-source-health
  // ===============================================================
  // Per intel source: status, last_message_observed_at,
  // classified_message_count_7d (already maintained on the row by
  // the meta-analyst), and a derived active_threats_produced_7d
  // count via provenance prefix match.
  //
  // Skips status='removed' / 'honeypot' rows from the response —
  // those aren't operationally relevant for the daily health view.
  // (The meta-analyst still tracks them; that's a separate route
  // surface in a future phase if we need it.)
  app.get(
    '/v1/admin/identity-shield/intel-source-health',
    { preHandler: requireBearer },
    withAdminAudit('identity-shield-intel-source-health', async (_req, reply) => {
      void emitMetric('identity_shield.admin_view_intel_source_health', {});

      // We join channels → active_threats LEFT, restricted to last
      // 7d for the threat-count rollup. provenance matches on a
      // case-insensitive LIKE prefix: 'telegram_channel:<id>:%' or
      // 'darknet_market:<id>:%'. The provenance shape is documented
      // in migration 071 + threatLandscapeAnalyst.ts.
      const res = await query<{
        id: string;
        source_kind: 'telegram' | 'darknet_market';
        source_handle: string;
        display_name: string;
        status: string;
        last_message_observed_at: Date | null;
        classified_message_count_7d: number;
        active_threats_produced_7d: string;
      }>(
        `SELECT
           c.id::TEXT                                          AS id,
           c.source_kind                                       AS source_kind,
           c.source_handle                                     AS source_handle,
           c.display_name                                      AS display_name,
           c.status                                            AS status,
           c.last_message_observed_at                          AS last_message_observed_at,
           c.classified_message_count_7d                       AS classified_message_count_7d,
           COALESCE(t.threat_count, 0)::TEXT                   AS active_threats_produced_7d
         FROM threat_intel_channels c
         LEFT JOIN (
           SELECT
             SPLIT_PART(provenance, ':', 1) AS prov_prefix,
             SPLIT_PART(provenance, ':', 2) AS source_id,
             COUNT(*) AS threat_count
           FROM active_threats
           WHERE last_seen_at >= NOW() - INTERVAL '7 days'
             AND (provenance LIKE 'telegram_channel:%' OR provenance LIKE 'darknet_market:%')
           GROUP BY prov_prefix, source_id
         ) t
           ON t.source_id = c.id::TEXT
          AND ((c.source_kind = 'telegram'       AND t.prov_prefix = 'telegram_channel')
            OR (c.source_kind = 'darknet_market' AND t.prov_prefix = 'darknet_market'))
         WHERE c.status NOT IN ('removed', 'honeypot')
         ORDER BY c.status ASC, c.classified_message_count_7d DESC, c.source_handle ASC
         LIMIT 200`,
      );
      const sources: IntelSourceHealthRow[] = res.rows.map((r) => ({
        id: r.id,
        source_kind: r.source_kind,
        source_handle: r.source_handle,
        display_name: r.display_name,
        status: r.status,
        last_message_observed_at: isoOrNull(r.last_message_observed_at),
        classified_message_count_7d: Number(r.classified_message_count_7d) || 0,
        active_threats_produced_7d: parseInt(r.active_threats_produced_7d, 10) || 0,
      }));
      return reply.send({ sources, window_days: 7 });
    }),
  );

  // ===============================================================
  // 5. GET /v1/admin/intel/candidates
  // ===============================================================
  // Pending-candidate review queue. Sorted by candidate_score DESC
  // then discovered_at DESC. Default status filter is 'pending'
  // (decision IS NULL).
  //
  // Query params:
  //   status      'pending' (default) | 'approved' | 'rejected'
  //   source_kind 'telegram' | 'darknet_market' (optional)
  //   limit       default 50, max 200
  app.get(
    '/v1/admin/intel/candidates',
    { preHandler: requireBearer },
    withAdminAudit('intel-candidates-list', async (req, reply) => {
      const q = (req.query as Record<string, string | undefined> | undefined) ?? {};
      const statusRaw = q['status'] ?? 'pending';
      const sourceKindRaw = q['source_kind'];
      const limit = parseLimit(req, 50, 200);

      // Whitelist the status values — never interpolate raw query
      // params into SQL even with the parameterized path, defense-
      // in-depth.
      let statusClause: string;
      const args: unknown[] = [];
      if (statusRaw === 'pending') {
        statusClause = 'decision IS NULL';
      } else if (statusRaw === 'approved') {
        statusClause = "decision = 'approved'";
      } else if (statusRaw === 'rejected') {
        statusClause = "decision = 'rejected'";
      } else {
        return reply.code(400).send({ error: 'invalid_status' });
      }

      let sourceKindClause = '';
      if (sourceKindRaw) {
        if (sourceKindRaw !== 'telegram' && sourceKindRaw !== 'darknet_market') {
          return reply.code(400).send({ error: 'invalid_source_kind' });
        }
        args.push(sourceKindRaw);
        sourceKindClause = ` AND source_kind = $${args.length}`;
      }

      args.push(limit);
      const limitParam = `$${args.length}`;

      void emitMetric('identity_shield.admin_view_intel_candidates', {
        status: statusRaw,
        source_kind: sourceKindRaw ?? 'any',
      });

      const res = await query<{
        id: string;
        source_kind: 'telegram' | 'darknet_market';
        source_handle: string;
        discovered_at: Date;
        rationale: unknown;
        candidate_score: string;
        decision: string | null;
        decided_at: Date | null;
      }>(
        `SELECT id::TEXT, source_kind, source_handle, discovered_at,
                rationale, candidate_score::TEXT AS candidate_score,
                decision, decided_at
           FROM threat_intel_candidates
          WHERE ${statusClause}${sourceKindClause}
          ORDER BY candidate_score DESC, discovered_at DESC
          LIMIT ${limitParam}`,
        args,
      );
      const candidates: CandidateRow[] = res.rows.map((r) => ({
        id: r.id,
        source_kind: r.source_kind,
        source_handle: r.source_handle,
        discovered_at: isoOrNull(r.discovered_at) ?? new Date(0).toISOString(),
        rationale: r.rationale,
        candidate_score: parseFloat(r.candidate_score) || 0,
        decision: r.decision,
        decided_at: isoOrNull(r.decided_at),
      }));
      return reply.send({ candidates, count: candidates.length, limit });
    }),
  );

  // ===============================================================
  // 6. POST /v1/admin/intel/candidates/:id/approve
  // ===============================================================
  // Promote a pending candidate → threat_intel_channels with
  // status='active'. Transactional: the INSERT and the candidate
  // UPDATE must both succeed or both roll back. Idempotency:
  //   - If the candidate is already approved → 409 conflict
  //   - If the candidate is already rejected → 409 conflict
  //   - If a channel with the same (source_kind, source_handle)
  //     already exists (collision) → 409 conflict
  //
  // The 409 on already-approved is the "no double-approve" guard.
  // The 409 on already-rejected is the "approval can't override
  // a rejection" guard. The 409 on channel-handle collision is the
  // "operator added this channel manually via another route"
  // guard — these UNIQUE collisions surface from the channels
  // table's UNIQUE (source_kind, source_handle) constraint.
  app.post(
    '/v1/admin/intel/candidates/:id/approve',
    { preHandler: requireBearer },
    withAdminAudit('intel-candidate-approve', async (req, reply) => {
      const params = req.params as { id?: string };
      const id = params.id;
      if (!id || !isUuid(id)) {
        return reply.code(400).send({ error: 'invalid_id' });
      }

      try {
        const result = await withTx(async (client) => {
          // Lock the row to prevent a concurrent approve/reject race.
          // FOR UPDATE on an unconditional SELECT — the explicit lock
          // means a second mutation arriving simultaneously waits for
          // this transaction to commit before reading the post-state.
          const candRes = await client.query<{
            id: string;
            source_kind: 'telegram' | 'darknet_market';
            source_handle: string;
            rationale: unknown;
            decision: string | null;
          }>(
            `SELECT id::TEXT, source_kind, source_handle, rationale, decision
               FROM threat_intel_candidates
              WHERE id = $1
              FOR UPDATE`,
            [id],
          );
          if (candRes.rowCount === 0) {
            return { status: 404 as const, body: { error: 'candidate_not_found' } };
          }
          const cand = candRes.rows[0]!;
          if (cand.decision !== null) {
            return {
              status: 409 as const,
              body: {
                error: 'candidate_already_decided',
                decision: cand.decision,
              },
            };
          }

          // Try to promote. UNIQUE (source_kind, source_handle) is
          // the collision boundary — if a channel with this handle
          // already exists, we 409 with a specific reason.
          let channel_id: string;
          try {
            const insRes = await client.query<{ id: string }>(
              `INSERT INTO threat_intel_channels
                 (source_kind, source_handle, display_name, status,
                  capability_tags, geo_relevance, added_by)
               VALUES ($1, $2, $3, 'active', '{}', '{}', NULL)
               RETURNING id::TEXT AS id`,
              [cand.source_kind, cand.source_handle, cand.source_handle],
            );
            if (insRes.rowCount === 0 || !insRes.rows[0]) {
              throw new Error('insert_returned_no_row');
            }
            channel_id = insRes.rows[0].id;
          } catch (err) {
            // pg error code 23505 = unique_violation.
            const e = err as { code?: string } & Error;
            if (e.code === '23505') {
              return {
                status: 409 as const,
                body: {
                  error: 'channel_handle_already_exists',
                  source_kind: cand.source_kind,
                  source_handle: cand.source_handle,
                },
              };
            }
            throw err;
          }

          await client.query(
            `UPDATE threat_intel_candidates
                SET decision = 'approved',
                    decided_at = NOW(),
                    decided_by = NULL
              WHERE id = $1`,
            [id],
          );

          return {
            status: 200 as const,
            body: {
              ok: true,
              candidate_id: id,
              channel_id,
              decision: 'approved',
            },
          };
        });

        void emitMetric('identity_shield.admin_candidate_decided', {
          decision: result.status === 200 ? 'approved' : 'rejected_by_state',
          outcome: String(result.status),
        });
        return reply.code(result.status).send(result.body);
      } catch (err) {
        // Re-throw — withAdminAudit catches + sanitizes. The
        // transaction's ROLLBACK is handled inside withTx().
        throw err;
      }
    }),
  );

  // ===============================================================
  // 7. POST /v1/admin/intel/candidates/:id/reject
  // ===============================================================
  // Reject a pending candidate. Stores an optional `reason` body
  // field on the rationale JSONB under `reject_reason`. Same
  // terminal-state semantics as approve: a candidate that's
  // already decided returns 409 — reject does NOT undo a prior
  // approval (the channel row is already in active service).
  app.post(
    '/v1/admin/intel/candidates/:id/reject',
    { preHandler: requireBearer },
    withAdminAudit('intel-candidate-reject', async (req, reply) => {
      const params = req.params as { id?: string };
      const id = params.id;
      if (!id || !isUuid(id)) {
        return reply.code(400).send({ error: 'invalid_id' });
      }

      const body = (req.body as Record<string, unknown> | null) ?? {};
      const reasonRaw = body['reason'];
      let reason: string | null = null;
      if (reasonRaw !== undefined && reasonRaw !== null) {
        if (typeof reasonRaw !== 'string') {
          return reply.code(400).send({ error: 'invalid_reason_type' });
        }
        // Bound the size + strip control chars so a hostile bearer
        // can't pack arbitrary data into the rationale JSONB.
        // eslint-disable-next-line no-control-regex
        reason = reasonRaw.replace(/[\x00-\x1f\x7f]/g, ' ').slice(0, 500).trim();
        if (reason.length === 0) reason = null;
      }

      try {
        const result = await withTx(async (client) => {
          const candRes = await client.query<{
            id: string;
            rationale: Record<string, unknown> | null;
            decision: string | null;
          }>(
            `SELECT id::TEXT, rationale, decision
               FROM threat_intel_candidates
              WHERE id = $1
              FOR UPDATE`,
            [id],
          );
          if (candRes.rowCount === 0) {
            return { status: 404 as const, body: { error: 'candidate_not_found' } };
          }
          const cand = candRes.rows[0]!;
          if (cand.decision !== null) {
            return {
              status: 409 as const,
              body: {
                error: 'candidate_already_decided',
                decision: cand.decision,
              },
            };
          }

          const rationale: Record<string, unknown> = {
            ...(cand.rationale ?? {}),
          };
          if (reason !== null) {
            rationale['reject_reason'] = reason;
            rationale['rejected_at'] = new Date().toISOString();
          }

          await client.query(
            `UPDATE threat_intel_candidates
                SET decision = 'rejected',
                    decided_at = NOW(),
                    decided_by = NULL,
                    rationale = $2::JSONB
              WHERE id = $1`,
            [id, JSON.stringify(rationale)],
          );

          return {
            status: 200 as const,
            body: {
              ok: true,
              candidate_id: id,
              decision: 'rejected',
              reason,
            },
          };
        });

        void emitMetric('identity_shield.admin_candidate_decided', {
          decision: result.status === 200 ? 'rejected' : 'rejected_by_state',
          outcome: String(result.status),
        });
        return reply.code(result.status).send(result.body);
      } catch (err) {
        throw err;
      }
    }),
  );

  // ===============================================================
  // 8. GET /v1/admin/intel/briefings/latest
  // ===============================================================
  // Single most-recent briefing. body_markdown is auto-generated
  // from aggregate stats and is supposed to be PII-free at the
  // input boundary (see threatLandscapeAnalyst.ts
  // BRIEFING_SYSTEM_PROMPT for the LLM contract).
  //
  // I-M4 fix: redactBriefingBody() runs as defense-in-depth before
  // sending. Scrubs digit-runs of 4+ and email-shaped tokens.
  // Emits a metric tagged with the redaction count so an operator
  // notices a sudden spike (which would indicate either a prompt
  // regression or upstream PII leakage). Per-call cost is O(N) on
  // the body length — briefings are short markdown documents
  // (<10KB), so the regex passes are negligible.
  app.get(
    '/v1/admin/intel/briefings/latest',
    { preHandler: requireBearer },
    withAdminAudit('intel-briefings-latest', async (_req, reply) => {
      void emitMetric('identity_shield.admin_view_intel_briefings_latest', {});

      const res = await query<{
        id: string;
        period_start: Date;
        period_end: Date;
        generated_at: Date;
        body_markdown: string;
        metrics_jsonb: unknown;
      }>(
        `SELECT id::TEXT, period_start, period_end, generated_at,
                body_markdown, metrics_jsonb
           FROM threat_landscape_briefings
          ORDER BY generated_at DESC
          LIMIT 1`,
      );
      if (res.rowCount === 0 || !res.rows[0]) {
        return reply.code(404).send({ error: 'no_briefing_yet' });
      }
      const r = res.rows[0];
      // I-M4: defense-in-depth digit/email redaction before send.
      const { redacted: body_markdown, redactions } = redactBriefingBody(r.body_markdown);
      void emitMetric('identity_shield.admin_briefing_redactions', {
        redactions: String(redactions),
        route: 'latest',
      });
      const body: BriefingFullRow = {
        id: r.id,
        period_start: r.period_start instanceof Date
          ? r.period_start.toISOString().slice(0, 10)
          : String(r.period_start).slice(0, 10),
        period_end: r.period_end instanceof Date
          ? r.period_end.toISOString().slice(0, 10)
          : String(r.period_end).slice(0, 10),
        generated_at: isoOrNull(r.generated_at) ?? new Date(0).toISOString(),
        body_markdown,
        metrics_jsonb: r.metrics_jsonb,
      };
      return reply.send(body);
    }),
  );

  // ===============================================================
  // 9. GET /v1/admin/intel/briefings
  // ===============================================================
  // Briefing index — NO body. Just (id, period_start, period_end,
  // generated_at) tuples ordered most-recent-first. Limit default
  // 20, max 200. The body is fetched separately by id via route 10
  // to bound the index-response size.
  app.get(
    '/v1/admin/intel/briefings',
    { preHandler: requireBearer },
    withAdminAudit('intel-briefings-list', async (req, reply) => {
      const limit = parseLimit(req, 20, 200);
      void emitMetric('identity_shield.admin_view_intel_briefings', {
        limit: String(limit),
      });

      const res = await query<{
        id: string;
        period_start: Date;
        period_end: Date;
        generated_at: Date;
      }>(
        `SELECT id::TEXT, period_start, period_end, generated_at
           FROM threat_landscape_briefings
          ORDER BY generated_at DESC
          LIMIT $1`,
        [limit],
      );
      const briefings: BriefingSummaryRow[] = res.rows.map((r) => ({
        id: r.id,
        period_start: r.period_start instanceof Date
          ? r.period_start.toISOString().slice(0, 10)
          : String(r.period_start).slice(0, 10),
        period_end: r.period_end instanceof Date
          ? r.period_end.toISOString().slice(0, 10)
          : String(r.period_end).slice(0, 10),
        generated_at: isoOrNull(r.generated_at) ?? new Date(0).toISOString(),
      }));
      return reply.send({ briefings, count: briefings.length, limit });
    }),
  );

  // ===============================================================
  // 10. GET /v1/admin/intel/briefings/:id
  // ===============================================================
  // Single briefing fetched by id. Returns body_markdown +
  // metrics_jsonb + the timestamp tuple.
  //
  // I-M4 fix: same redactBriefingBody() defense-in-depth pass as the
  // /latest route. The LLM is supposed to receive only aggregate
  // stats but we don't trust that to be load-bearing — a
  // hallucinated digit-run would otherwise reach the operator.
  app.get(
    '/v1/admin/intel/briefings/:id',
    { preHandler: requireBearer },
    withAdminAudit('intel-briefing-by-id', async (req, reply) => {
      const params = req.params as { id?: string };
      const id = params.id;
      if (!id || !isUuid(id)) {
        return reply.code(400).send({ error: 'invalid_id' });
      }
      void emitMetric('identity_shield.admin_view_intel_briefing_by_id', {});

      const res = await query<{
        id: string;
        period_start: Date;
        period_end: Date;
        generated_at: Date;
        body_markdown: string;
        metrics_jsonb: unknown;
      }>(
        `SELECT id::TEXT, period_start, period_end, generated_at,
                body_markdown, metrics_jsonb
           FROM threat_landscape_briefings
          WHERE id = $1
          LIMIT 1`,
        [id],
      );
      if (res.rowCount === 0 || !res.rows[0]) {
        return reply.code(404).send({ error: 'briefing_not_found' });
      }
      const r = res.rows[0];
      // I-M4: defense-in-depth digit/email redaction before send.
      const { redacted: body_markdown, redactions } = redactBriefingBody(r.body_markdown);
      void emitMetric('identity_shield.admin_briefing_redactions', {
        redactions: String(redactions),
        route: 'by_id',
      });
      const body: BriefingFullRow = {
        id: r.id,
        period_start: r.period_start instanceof Date
          ? r.period_start.toISOString().slice(0, 10)
          : String(r.period_start).slice(0, 10),
        period_end: r.period_end instanceof Date
          ? r.period_end.toISOString().slice(0, 10)
          : String(r.period_end).slice(0, 10),
        generated_at: isoOrNull(r.generated_at) ?? new Date(0).toISOString(),
        body_markdown,
        metrics_jsonb: r.metrics_jsonb,
      };
      return reply.send(body);
    }),
  );
}
